### ISSUE TITLE
deprecated or removed shorewall.conf options

### ISSUE THREAD

**Issue by adamharm** [arillso/ansible.shorewall#7]
I am using shorewall 5.1.12.2 and receive the following warnings when testing the shorewall configuration:

WARNING: The CHAIN_SCRIPTS configuration option is no longer supported /etc/shorewall/shorewall.conf (line 25)
WARNING: Option INLINE_MATCHES=Yes is deprecated /etc/shorewall/shorewall.conf (line 46)
WARNING: The MODULE_SUFFIX configuration option is no longer supported /etc/shorewall/shorewall.conf (line 73)

I am happy to help code up a fix for this problem if I can get some suggestions on where to start.  Is it best to modify the shorewall.conf.j2 template to remove some variables if they exist for certain versions of shorewall?

**Comment by adamharm** [comment]
Also, two other options also return a warning:
The recommendation for drop_default and reject_default has changed in 5.1, the new values are:
drop_default: "Broadcast(DROP),Multicast(DROP)"
reject_default: "Broadcast(DROP),Multicast(DROP)"

Is it best to just have individual shorewall.conf files for 4, 5.0, 5.1?

**Comment by sbaerlocher** [comment]
Creating a config for each version would mean a major rebuilding, since all config entries are stored here in an array. 
Link https://github.com/arillso/ansible.shorewall/blob/master/vars/main.yml

I would determine the installed shorewall version and then insert the correct value depending on the version.

tasks:
```
- name: get shorewall version
  shell: shorewall version
  register: register_shorewall_version

- name: shorewall version
  set_fact:
    shorewall_version: "{{ register_shorewall_version.stdout }}"
```
vars:
```
shorewall_conf_base:
  drop_default: "{{ shorewall_drop_default[shorewall_version] }}"
```
default:
```
shorewall_drop_default:
  5.0.4: "Drop"
  5.1.0: "Broadcast(DROP),Multicast(DROP)"
```
Is it understood?
Would you like to make the adjustments?
